apiVersion: batch/v1
kind: CronJob
metadata:
  name: custodian-cronjob
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: custodian-sa
          containers:
            - name: custodian
              image: custodian:latest
              imagePullPolicy: IfNotPresent
              command: ["validate"]  # TODO: Change this to the command you want to run
          restartPolicy: OnFailure