apiVersion: batch/v1
kind: CronJob
metadata:
  name: custodian-cronjob
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: custodian-sa
          containers:
            - name: custodian
              image: softwareplant/custodian:0.1.0-alpha.1
              imagePullPolicy: Always
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: dockerhub-credential