# GitHub Actions workflow to validate Cloud Custodian policies
name: Validate Policy

on:
  push:                # Trigger the workflow on push events
    branches:
      - main       # Only trigger when pushing to the 'main' branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Upgrade pip to ensure the latest version is used
      - name: Upgrade pip
        run: pip install --upgrade pip

      # Step 4: Install Cloud Custodian packages and its extensions for Azure and GCP
      - name: Install Custodian
        run: pip install c7n c7n_azure c7n_gcp

      # Step 5: Validate the Cloud Custodian policy file
      - name: Validate policy file
        run: custodian validate CloudCustodian/policies/policy.yml
